# fly.toml app configuration file generated for txti-clone on 2023-06-18T02:36:50+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "txti-clone"
primary_region = "sin"
console_command = '/rails/bin/rails console'

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = './bin/rails db:prepare'

[processes]
  web = "./bin/rails server"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]
  [http_service.concurrency]
    type = "requests"
    soft_limit = 16
    hard_limit = 50

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
