# fly.toml app configuration file generated for txti-clone on 2023-06-18T02:36:50+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "txti-clone"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  PRIMARY_REGION = "sin"

[processes]
  web = "./bin/rails server"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]
  [http_service.concurrency]
    type = "requests"
    soft_limit = 20
    hard_limit = 25

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
